# Generated by Django 4.2.9 on 2024-07-26 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0049_costoanterior_apoyo_salud'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatos',
            name='cargo_distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_distrito', to='proyecto.distrito'),
        ),
    ]
