# Generated by Django 4.2.9 on 2024-07-26 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0050_userdatos_cargo_distrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatos',
            name='distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.distrito'),
        ),
    ]
