# Generated by Django 4.2.9 on 2024-09-04 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0051_alter_userdatos_distrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperfil',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdatos',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdatos',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.perfil'),
        ),
        migrations.AlterField(
            model_name='historicalperfil',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
