# Generated by Django 4.2.9 on 2024-09-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0052_historicalperfil_usuario_perfil_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatos',
            name='cargo_distrito',
        ),
        migrations.RemoveField(
            model_name='userdatos',
            name='numero_de_trabajador',
        ),
        migrations.RemoveField(
            model_name='userdatos',
            name='user',
        ),
        migrations.AlterField(
            model_name='userdatos',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_datos', to='proyecto.perfil'),
        ),
    ]
