# Generated by Django 4.2.9 on 2024-09-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0053_remove_userdatos_cargo_distrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosisr',
            name='activo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='datosisr',
            name='indicador',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
