# Generated by Django 4.2.9 on 2024-09-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0054_datosisr_activo_datosisr_indicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='salariodatos',
            name='activo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variables_imss_patronal',
            name='activo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
