# Generated by Django 4.2.9 on 2024-09-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0055_salariodatos_activo_variables_imss_patronal_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablavacaciones',
            name='activo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tablavacaciones',
            name='indicador',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
