# Generated by Django 4.2.9 on 2024-08-05 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0051_alter_userdatos_distrito'),
        ('esquema', '0016_alter_solicitud_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonosolicitado',
            name='trabajador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.perfil'),
        ),
    ]
