# Generated by Django 4.2.9 on 2024-08-05 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esquema', '0017_alter_bonosolicitado_trabajador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonosolicitado',
            name='puesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='esquema.puesto'),
        ),
    ]
