# Generated by Django 4.2.9 on 2024-09-09 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0053_remove_userdatos_cargo_distrito_and_more'),
        ('esquema', '0019_remove_bonosolicitado_distrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.distrito'),
        ),
    ]
