# Generated by Django 4.2.9 on 2024-09-12 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esquema', '0020_solicitud_distrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonosolicitado',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonos_solicitados', to='esquema.solicitud'),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to='esquema.solicitud'),
        ),
    ]
