# Generated by Django 4.2.7 on 2024-06-02 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0025_alter_prenominaincidencias_prenomina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenominaincidencias',
            name='incapacidades_rango',
        ),
        migrations.AlterField(
            model_name='pagar_incapacidad',
            name='incapacidades_rango',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenomina.incidenciasrango'),
        ),
        migrations.DeleteModel(
            name='IncapacidadesRango',
        ),
    ]
