# Generated by Django 4.2.9 on 2024-09-12 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0053_remove_userdatos_cargo_distrito_and_more'),
        ('prenomina', '0039_alter_aguinaldo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenomina',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.distrito'),
        ),
    ]
