# Generated by Django 4.2.9 on 2024-09-24 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0053_remove_userdatos_cargo_distrito_and_more'),
        ('prenomina', '0040_prenomina_distrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenomina',
            name='fonacot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='prenomina',
            name='indicador_isr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prenomina',
            name='infonavit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='prenomina',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='prenomina',
            name='sdi_imss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='prenomina',
            name='tipo_contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.contrato'),
        ),
        migrations.AddField(
            model_name='prenomina',
            name='uma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.salariodatos'),
        ),
    ]
