# Generated by Django 4.2.9 on 2024-09-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0042_prenomina_imss_patronal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prenomina',
            old_name='uma',
            new_name='salario_datos',
        ),
    ]
