# Generated by Django 4.2.9 on 2024-09-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina', '0043_rename_uma_prenomina_salario_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenomina',
            name='apoyo_pasajes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
    ]
